from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime

# --- Product Schemas ---
class ProductBase(BaseModel):
    name: str
    description: Optional[str] = None
    price: float
    category: str
    image_url: Optional[str] = None
    stock: int = 100

class ProductCreate(ProductBase):
    pass

class Product(ProductBase):
    id: int
    created_at: datetime

    class Config:
        from_attributes = True


# --- Cart Schemas ---
class CartItemBase(BaseModel):
    product_id: int
    quantity: int = Field(default=1, ge=1)

class CartItemCreate(CartItemBase):
    pass

class CartItemUpdate(BaseModel):
    quantity: int = Field(..., ge=1)

class CartItem(BaseModel):
    id: int
    cart_id: int
    product_id: int
    quantity: int
    product: Product

    class Config:
        from_attributes = True

class Cart(BaseModel):
    id: int
    session_id: str
    created_at: datetime
    updated_at: datetime
    items: List[CartItem] = []

    class Config:
        from_attributes = True


# --- Chat Schemas ---
class ChatMessage(BaseModel):
    sender: str  # "user" or "bot"
    text: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    # Optional dynamic UI widgets generated by LLM (like product suggestions)
    products: Optional[List[Product]] = None

class ChatRequest(BaseModel):
    session_id: str
    message: str
    use_voice: bool = False

class ChatResponse(BaseModel):
    session_id: str
    reply: str
    products: Optional[List[Product]] = None
    voice_url: Optional[str] = None  # Future voice stream option


# --- User & Auth Schemas ---
class UserCreate(BaseModel):
    username: str
    email: str
    password: str

class UserLogin(BaseModel):
    username: str
    password: str

class UserResponse(BaseModel):
    id: int
    username: str
    email: str
    created_at: datetime

    class Config:
        from_attributes = True

class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    user: UserResponse


